INSERT INTO FLIGHT (ID, AIRLINE, FLIGHT_NUMBER, SOURCE, DESTINATION, PRICE)
VALUES (1, 'Indigo', '6E-123', 'Mumbai', 'Delhi', 4500.00);

INSERT INTO FLIGHT (ID, AIRLINE, FLIGHT_NUMBER, SOURCE, DESTINATION, PRICE)
VALUES (2, 'Air India', 'AI-202', 'Bangalore', 'Kolkata', 6000.00);
